### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by KyleKing** [SterlingButters/plaidash#3]
Thanks for building this component! I'm using it in a personal project and would be happy to help contribute

Initially, I couldn't get the usage example to work until I updated the `api_version` to `2019-05-29`

My app has Bulma CSS and an absolute-positioned side-menu, so I also had to set the Plaid iframe height to 100vh, otherwise it only appeared on the top 1/6 of the screen

**Comment by SterlingButters** [comment]
Hey @KyleKing

I'd love a fellow contributor/maintainer. I was satisfied with the functionality of the project so I haven't come back to it in awhile but I know the next big TODO was to get the token property to function as an input instead of having to grab it from the state of the component. 

Glad someone else was able to benefit from the project!

**Comment by KyleKing** [comment]
For the project that I intended to build with Plaid, I'm using Metabase as a front-end since it is great for EDA out-of-the-box vs. Dash which was just too much effort for one-off analysis

In my fork, I did make some changes, so I'll keep it around, but two years later 😅 they probably aren't all that helpful and a chunk of the diff is some auto-formatting that would need to be undone

The project did help me experiment with the Plaid API, which was really helpful though!
